version: '2'
services:
  #  check4facts-app:
  #    image: check4facts
  #    environment:
  #      - _JAVA_OPTIONS=-Xmx512m -Xms256m
  #      - SPRING_PROFILES_ACTIVE=prod,swagger
  #      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
  #      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
  #      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://check4facts-postgresql:5432/check4facts
  #      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  #      - SPRING_DATA_JEST_URI=http://check4facts-elasticsearch:9200
  #      - SPRING_ELASTICSEARCH_REST_URIS=http://check4facts-elasticsearch:9200
  #    ports:
  #      - 8080:8080
  check4facts-postgresql:
    extends:
      file: postgresql.yml
      service: check4facts-postgresql
  check4facts-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: check4facts-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: always
    environment:
      - LT_LOAD_ONLY=en,el
    ports:
      - '5000:5000'
  searxng:
    image: searxng/searxng
    ports:
      - '8081:8080'
    environment:
      - BASE_URL=http://localhost:8081/
      - INSTANCE_NAME=check4facts-searxng
    volumes:
      - ./searxng:/etc/searxng
