version: '3'
name: 'check4facts'
services:
  c4f:
    image: check4facts
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://check4facts-postgresql:5432/check4facts
      - JHIPSTER_SLEEP=2 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://check4facts-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://check4facts-elasticsearch:9200
    ports:
      - 9000:8080
    networks:
      - docker_default
networks:
  docker_default:
    external:
      name: docker_default
