version: '2'
services:
  check4facts-postgresql:
    image: postgres:12.3
    volumes:
      - /data/postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=check4facts
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
